### ISSUE TITLE
MCP4725 library fails for Arduino Giga R1 Wifi board

### ISSUE THREAD

**Issue by Fran-3** [RobTillaart/MCP4725#29]
Unable to get the MCP4725 library examples to work with the Arduino Giga R1 Wifi board.
Works with UNO R3 but not Giga R1 Wifi board.
Maybe because there are 3-I2C ports on the Giga R1 Wifi board??? 
I'm unsure the reason.
Thank you.

**Comment by RobTillaart** [comment]
The MCP4725 works from 2.7-5.5 Volt so the 3V3 of the Giga should be no problem.

Did you add pull up resistors (4K7 ..2K2) to the SDA and SCL lines used?
For the 5V UNO the signals are "stronger" than the 3V3 so the pull ups are not always needed on a UNO.

**Comment by RobTillaart** [comment]
> Do you have a link to its specs?

Found this one - https://docs.arduino.cc/tutorials/giga-r1-wifi/cheat-sheet#i2c-pins

If you choose another as the default you need to add a parameter in the constructor of the MCP4725.

**Comment by RobTillaart** [comment]
Installed the GIGA R1 compiler (IDE1.8.19) and two examples compiled with no errors. 
(there are warnings about the CAN BUS messages code, but those are not part of this library)

Do you have compile errors or runtime errors? (should have been my first question).

**Comment by Fran-3** [comment]
It's working now.
Apologies to all. There are three i2c ports on the Arduino Giga R1 Wifi.
I was confused about which was which.
It appears the "default" pair are I2C2_SDA and I2C2_SCL located at the bottom right of the board... the other end from the USB connectors.
Now the question how do I apply the code to either I2C4 or I2C1?
I looked in the header file but was unable to determine if modifying something there would apply the code to either of the remaining two i2c channels.
Thanks for any help!

**Comment by RobTillaart** [comment]
You can set the I2C port in the constructor, the last parameter, which is default Wire.
Set it to Wire1 or Wire2, see board specs how it is mapped

**Comment by Fran-3** [comment]
Thank you Rob. Actually I'm looking for a simple way to tell an DAC on the i2c buss to output a constant DC voltage.
It would hold that DC out until, depending on circumstances, my program told it to change to a different DC voltage.
And I would like to do this in the a separate function that could be called from either void setup or  void loop as necessary.
I think I can modify the smooth2value code to do this but it seems like a lot of overhead for such a simple task.
Anyhow, food for thought for you. And, thanks for your library and your response!

**Comment by RobTillaart** [comment]
As the thread is silent for a week I assume the issue is solved, otherwise feel free to reopen it.
